# Generated by Django 4.0.4 on 2022-10-16 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_citizen_lastname_alter_citizen_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecycleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=3)),
                ('unit', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('dateSubmitted', models.DateTimeField(default=datetime.datetime(2022, 10, 16, 23, 59, 38, 592236))),
                ('status', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
