# Generated by Django 4.0.4 on 2022-10-16 23:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collector_material_recyclerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclerequest',
            name='citizen',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.citizen'),
        ),
        migrations.AddField(
            model_name='recyclerequest',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.material'),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 0, 2, 33, 276893)),
        ),
    ]
