# Generated by Django 4.0.4 on 2022-10-17 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recyclerequest_citizen_recyclerequest_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='username',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 16, 18, 43, 272199)),
        ),
    ]
