# Generated by Django 4.0.4 on 2022-10-17 21:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_alter_confirmationcode_expirationdate_and_more'),
        ('core', '0006_remove_citizen_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user'),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 22, 4, 11, 919902)),
        ),
    ]
