# Generated by Django 4.0.4 on 2022-10-17 22:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_alter_confirmationcode_expirationdate_and_more'),
        ('core', '0007_citizen_user_alter_recyclerequest_datesubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user'),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 22, 56, 54, 101319)),
        ),
    ]
