# Generated by Django 4.1.2 on 2022-10-30 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_alter_confirmationcode_expirationdate_and_more'),
        ('core', '0009_alter_recyclerequest_datesubmitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='collector',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='collector',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user'),
        ),
        migrations.AddField(
            model_name='recyclerequest',
            name='Collector',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.collector'),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='dateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 12, 59, 1, 877257, tzinfo=datetime.timezone.utc)),
        ),
    ]
